import type { Team } from "../types/career.ts";
export const teamName = (teams: Team[], id: string) =>
  teams.find((team) => team.id === id)?.name ?? "Unknown team";
const logoSlugById: Record<string, string> = {
  ATL: "hawks",
  BOS: "celtics",
  BKN: "nets",
  CHA: "hornets",
  CHI: "bulls",
  CLE: "cavaliers",
  DAL: "mavericks",
  DEN: "nuggets",
  DET: "pistons",
  GSW: "warriors",
  HOU: "rockets",
  IND: "pacers",
  LAC: "clippers",
  LAL: "lakers",
  MEM: "grizzlies",
  MIA: "heat",
  MIL: "bucks",
  MIN: "timberwolves",
  NOP: "pelicans",
  NYK: "knicks",
  OKC: "thunder",
  ORL: "magic",
  PHI: "76ers",
  PHX: "suns",
  POR: "trailblazers",
  SAC: "kings",
  SAS: "spurs",
  TOR: "raptors",
  UTA: "jazz",
  WAS: "wizards",
};
// Logo image URL for a team, or null for custom teams without a bundled logo.
export const teamLogo = (id: string) =>
  logoSlugById[id] ? `/teamLogos/${logoSlugById[id]}.png` : null;
export const modernTeams: Team[] = [
  ["ATL", "Atlanta Hawks"],
  ["BOS", "Boston Celtics"],
  ["BKN", "Brooklyn Nets"],
  ["CHA", "Charlotte Hornets"],
  ["CHI", "Chicago Bulls"],
  ["CLE", "Cleveland Cavaliers"],
  ["DAL", "Dallas Mavericks"],
  ["DEN", "Denver Nuggets"],
  ["DET", "Detroit Pistons"],
  ["GSW", "Golden State Warriors"],
  ["HOU", "Houston Rockets"],
  ["IND", "Indiana Pacers"],
  ["LAC", "Los Angeles Clippers"],
  ["LAL", "Los Angeles Lakers"],
  ["MEM", "Memphis Grizzlies"],
  ["MIA", "Miami Heat"],
  ["MIL", "Milwaukee Bucks"],
  ["MIN", "Minnesota Timberwolves"],
  ["NOP", "New Orleans Pelicans"],
  ["NYK", "New York Knicks"],
  ["OKC", "Oklahoma City Thunder"],
  ["ORL", "Orlando Magic"],
  ["PHI", "Philadelphia 76ers"],
  ["PHX", "Phoenix Suns"],
  ["POR", "Portland Trail Blazers"],
  ["SAC", "Sacramento Kings"],
  ["SAS", "San Antonio Spurs"],
  ["TOR", "Toronto Raptors"],
  ["UTA", "Utah Jazz"],
  ["WAS", "Washington Wizards"],
].map(([id, name]) => ({ id, name, source: "modern" }));
